### ISSUE TITLE
[Bug] Le branch in expo non sono tutte

### ISSUE THREAD

**Issue by bob27aggiustatutto** [PoliNetworkOrg/PoliFemo#100]
![immagine](https://user-images.githubusercontent.com/120955097/212557355-98587159-34da-4d50-b69f-0a157cf82de0.png)

La lista delle branch di github non corrisponde a quella che c'è su expo

**Comment by toto04** [comment]
colpa mia ho rotto lo script per eliminare i branch non utilizzati e li elimina tutti per sbaglio, sto lavorando a un fix

**Comment by toto04** [comment]
ok ho fixato il problema che ha causato la rimozione dei branch in #103, i branch attualmente aperti che non sono stati pubblicati su EAS verranno automaticamente pubblicati al primo push o possono essere manualmente pubblicati facendo un checkout nel branch in questione e eseguendo il comando
```sh
eas update --auto
```
