### ISSUE TITLE
Rotellina GPS presente anche se non c'è segnale o c'è il gps spento

### ISSUE THREAD

**Issue by bob27aggiustatutto** [PoliNetworkOrg/PoliFemo#101]
![immagine](https://user-images.githubusercontent.com/120955097/212564226-268302c8-8109-4bdb-ab13-fdc10e5af56e.png)

![immagine](https://user-images.githubusercontent.com/120955097/212564230-236ac8d7-6c4f-4034-8af2-2ce1de18dcbe.png)

**Comment by toto04** [comment]
probabilmente la cosa migliore sarebbe avvisare l'utente che il segnale GPS non c'è, la rotellina è molto carina mentre si aspetta la risposta di `Location.reverseGeocodeAsync()`, se l'utente ha negato i permessi è inutile, tanto vale mostrare l'icona della freccia della localizzazione barrata o qualcosa del genere, ipoteticamente con un tasto per aprire la pagina impostazioni dei permessi di geolocalizzazione in caso l'utente abbia cambiato idea. Sono idee di cui dobbiamo parlare col team di design queste

**Comment by bob27aggiustatutto** [comment]
https://app.clickup.com/t/860pjtw72

**Comment by toto04** [comment]
fixed in teoria
