### ISSUE TITLE
Ordinamento aule libere

### ISSUE THREAD

**Issue by bob27aggiustatutto** [PoliNetworkOrg/PoliFemo#112]
Con che criterio vengono ordinati gli edifici?
![immagine](https://user-images.githubusercontent.com/120955097/215344463-aa076ab8-751d-4256-a803-5de887ef3bb3.png)

**Comment by lups2000** [comment]
Attualmente faccio la chiamata all’api, ottengo la lista delle aule libere e le raggruppo in edifici.È ancora una bozza per vedere se funzionava la call all’api!Potrei fare ordine crescente volendo

**Comment by bob27aggiustatutto** [comment]
Attendiamo il parere degli altri, comunque un qualche criterio d'ordinamento dobbiamo definirlo

**Comment by bob27aggiustatutto** [comment]
https://app.clickup.com/t/862j586kh

**Comment by toto04** [comment]
ordinamento numerico nell'elenco, in base alla distanza nella lista della posizione, se gli edifici sono in ordine sbagliato dovremmo aprire una issue nel backend, se è un problema fixarlo nel backend possiamo riordinarli noi
