### ISSUE TITLE
Tasto "imposta termine autocancellazione"

### ISSUE THREAD

**Issue by bob27aggiustatutto** [PoliNetworkOrg/PoliFemo#116]
E' un timestamp (nell'ordine di grandezza di anni e mesi) da inviare al backend, il backend predisporrà sia l'api per cambiare il valore sia l'api per ricevere il valore.

Questa api funziona solo per gli utenti autenticati (che han fatto login o con polimi o microsoft)

**Comment by bob27aggiustatutto** [comment]
occhio che comunque non consentiamo un valore superiore a 5 anni

**Comment by bob27aggiustatutto** [comment]
e non inferiore a 30 giorni, se uno vuole cancellarsi subito ha il tasto

**Comment by toto04** [comment]
per dire la mia opinione, non mi piace l'idea di dare troppe opzioni all'utente certe volte, sarebbe un po' confusionario, se l'utente vuole cancellarsi in un momento specifico ha il tasto appunto, se no è perché non gliene frega un cazzo e lo cancelliamo quando pensiamo sia giusto noi
l'utente ha già la sua scelta sotto forma del tasto, non c'è bisogno di dargli ancora più opzioni.
detto questo comunque sì sarebbe una cazzata da implementare se è una feature voluta no prob

**Comment by bob27aggiustatutto** [comment]
![immagine](https://user-images.githubusercontent.com/120955097/215886427-bfae30c7-2233-4c77-bf2e-92224605748e.png)

deve venire una roba così

**Comment by bob27aggiustatutto** [comment]
https://app.clickup.com/t/86779vfv8
