### ISSUE TITLE
[Bug] Unicode non gestisto bene nella ricerca gruppi

### ISSUE THREAD

**Issue by bob27aggiustatutto** [PoliNetworkOrg/PoliFemo#119]

**Comment by bob27aggiustatutto** [comment]
![immagine](https://user-images.githubusercontent.com/120955097/216016376-797060aa-2a90-42b0-ad10-1232d104b449.png)

**Comment by DiegoZaff** [comment]
Ma sbaglio o è un problema del json?

Cioè, la risposta che arriva dal server è ad esempio "u00adu0192u00d6u00ea" quando dovrebbe essere "\u00ad\u0192\u00d6\u00ea"

**Comment by bob27aggiustatutto** [comment]
![immagine](https://user-images.githubusercontent.com/120955097/216075273-dd571767-1f14-45d6-8da9-f294f8e86af2.png)

E' lo stesso json che usa il sito?

![immagine](https://user-images.githubusercontent.com/120955097/216075505-7d9f75d6-ef89-47f9-a682-c510230d7e7c.png)


https://github.com/PoliNetworkOrg/polinetworkWebsiteData/blob/main/groupsGenerated.json

**Comment by toto04** [comment]
<img width="778" alt="image" src="https://user-images.githubusercontent.com/34661230/216601417-3b34ca00-b054-4ffa-b08e-c5e9427bbabd.png">
è un problema del backend, questo è quello che viene restituito dall'endpoint

**Comment by bob27aggiustatutto** [comment]
Ma perché fate le chiamate al backend e non al json hostato su github?

**Comment by toto04** [comment]
questa domanda la devi fare a chi ha fatto l'endpoint, però boh pratico filtrare usando le query all'endpoint

**Comment by bob27aggiustatutto** [comment]
"pratico" va definito

* Intendi che è più veloce scrivere il codice lato frontend?
* Intendi che è più leggera la computazione lato frontend?

Di entrambe le cose mi interessa poco, preferisco alleggerire il carico del nostro backend, non trovi?

**Comment by bob27aggiustatutto** [comment]
https://app.clickup.com/t/860pt0zgv

**Comment by bob27aggiustatutto** [comment]
Le api backend per i gruppi spariscono, il frontend si sposta ad usare direttamente il json che sta nella repo del network (quindi hostato da github)

https://github.com/PoliNetworkOrg/PoliFemoBackend/pull/110

**Comment by bob27aggiustatutto** [comment]
Nota bene che il frontend se vuole può fare caching del json di modo da non fare 500 query a github

**Comment by toto04** [comment]
fixed with #154
