### ISSUE TITLE
[Design] Se l'informazione dei membri non c'è (gruppo per gruppo), non visualizzarla

### ISSUE THREAD

**Issue by bob27aggiustatutto** [PoliNetworkOrg/PoliFemo#120]
![immagine](https://user-images.githubusercontent.com/120955097/216016746-7f10f842-b231-433b-83bd-8c97cc658750.png)

Diventa così

![immagine](https://user-images.githubusercontent.com/120955097/216016941-2b1962b4-aab4-470c-9216-f88e2f014ce8.png)

Con la scritta centrata verticalmente

Questo solo nel caso non sia presente l'informazione dei membri per quel gruppo

**Comment by DiegoZaff** [comment]
Ok quindi per il momento tolgo quella scritta ovunque dato che non abbiamo le informazioni sul numero di membri.

**Comment by bob27aggiustatutto** [comment]
Aggiorni il componente "risultato gruppo" (e se non lo esiste lo crei) per gestire entrambe le casistiche, gruppo per gruppo

**Comment by DiegoZaff** [comment]
Ok per il momento ho supposto che quel campo inesistente si chiami members, in futuro quando sarà effettivamente aggiunto gli metterò il nome corretto.
