### ISSUE TITLE
Spostare tutti i tasti di pagine "not implemented yet" nel "aggiungi feature"

### ISSUE THREAD

**Issue by bob27aggiustatutto** [PoliNetworkOrg/PoliFemo#126]

**Comment by bob27aggiustatutto** [comment]
Se una feature manca

![immagine](https://user-images.githubusercontent.com/120955097/216775793-442e5c31-4239-499d-8bbf-dd7540dec15c.png)

non bisogna mostrarla nel menu ma nasconderla sotto 
![immagine](https://user-images.githubusercontent.com/120955097/216775809-1eb121bb-733d-43ce-aeb4-b2460e70e0f8.png)

![immagine](https://user-images.githubusercontent.com/120955097/216775815-6d020921-743f-4c26-a016-028c75c427f2.png)


Non deve potere uscire da lì, se qualcuno prova a cliccarla esce un toast che dice che non è ancora pronta
https://developer.android.com/guide/topics/ui/notifiers/toasts

Quando sarà pronta sarà automaticamente mossa nel menu

**Comment by toto04** [comment]
c'è già la pagina "not implemented", non penso che sia molto sensato cambiare un placeholder con un altro placeholder, sono sempre dei placeholder e non saranno mai nella versione finale

**Comment by bob27aggiustatutto** [comment]
Serve se vogliamo fare una specie di "preview" per future features, facendolo comparire nell'aggiungi

**Comment by bob27aggiustatutto** [comment]
palesemente non prioritaria, questa issue

**Comment by toto04** [comment]
Parli di lasciare tasti in uno stato di "preview" in produzione? tipo come sneak-peak di feature non ancora implementate?
perché in tal caso non sono sicuro, ma ho paura che non rispettino le guidelines di apple https://developer.apple.com/app-store/review/guidelines/#app-completeness

(anche se l'app ufficiale del poli ha tasti per feature non ancora implementate effettivamente, ma yet again l'app ufficiale è chiaramente contro il punto [4.2](https://developer.apple.com/app-store/review/guidelines/#minimum-functionality), sicuro noi non siamo il poli e non avremo le stesse concessioni)

se invece stai parlando di tenere questa cosa solo nelle versioni beta reitero, un placeholder è sempre e solo un placeholder

**Comment by bob27aggiustatutto** [comment]
Stavo dicendo la prima

Per rispettare le regole degli store è possibile creare una sezione "future features"? 
Non come tasti ma come testo, come info, quasi come fosse una news (articolo)

**Comment by bob27aggiustatutto** [comment]
https://app.clickup.com/t/860pub59y

**Comment by toto04** [comment]
ci sarà un mini rework del menu, questa feature request non è più rilevante
