### ISSUE TITLE
Fine articolo, gestione foto

### ISSUE THREAD

**Issue by bob27aggiustatutto** [PoliNetworkOrg/PoliFemo#128]
![Screenshot_20230204-222912_Expo Go](https://user-images.githubusercontent.com/120955097/216790337-36c3607f-5fc5-4046-b4fe-1209bb61a860.png)

1. Se c'è una sola foto, cliccandoci la espande in un visualizzatore foto che consente lo zoom
2. Se c'è più di una foto, come sopra ma con uno slider per scorrere fra le foto

**Comment by lups2000** [comment]
@DiegoZaff ora le foto si vedono bene nello schermo, però ho notato che lo zoom è un pò insolito. Nel senso che non zooma nel punto in cui con le due dita si fa il gesto. Possibile? (L'ho testato solo su IOS)

**Comment by DiegoZaff** [comment]
Si allora, lo zoom al momento è disabilitato in tutta la webview.
Sto lavorando a un metodo di visualizzazione delle foto a schermo intero che scorpori le immagini dalla webview.

**Comment by DiegoZaff** [comment]
Che comportamento vogliamo avere per lo zoom? Perchè oggi ho sbattuto la testa per cercare di fare funzionare un pinch zoom + panning ma con poco successo. Un altra alternativa potrebbe essere un zoom con doppio click + panning.
Chiedo cosi mi concentro su ciò che effettivamente serve.

**Comment by bob27aggiustatutto** [comment]
Se vuoi fare qualcosa una sola volta, allora devi sentire il design

Non serve per l'avvio della beta quindi prenditela pure con comoda

(= senti i designers)

**Comment by DiegoZaff** [comment]
Okay

**Comment by DiegoZaff** [comment]
Ancora non ho avuto modo di chiedere alle designers ma intanto sono riuscito a fare il pinch zoom + panning laterale con tutto il controllo delle misure.

**Comment by bob27aggiustatutto** [comment]
Molto bene

1. Ora manca solo lo slider/slideshow per cambiare fra foto
2. Fai un po' più grande la x sugli schermi ad altra risoluzione

**Comment by bob27aggiustatutto** [comment]
Continua in #134

**Comment by bob27aggiustatutto** [comment]
https://app.clickup.com/t/863g0bfa4
