### ISSUE TITLE
Sezione "about" sotto impostazioni

### ISSUE THREAD

**Issue by bob27aggiustatutto** [PoliNetworkOrg/PoliFemo#131]
Serve una sezione "about" nelle impostazioni che abbia delle sottosezioni. Per sezione o sottosezione si intende una pagina dedicata

`About` conterrà:

1. Informazioni generiche sull'app, descrizione, storia, ecc
2. Versione (nominale, data della build, ecc)
3. Crediti
4. Librerie usate e licenze
5. Tasto che rimanda alla sezione privacy policy (che è una sezione a sé)

**Comment by bob27aggiustatutto** [comment]
6. Sezione "codice sorgente" con i link alle nostro 4 repository

**Comment by bob27aggiustatutto** [comment]
7. Log

**Comment by toto04** [comment]
ma per 4 repositories intendi anche aggiungere polifemodocs e polifemodashboard? la usiamo polifemodocs? e boh la dashboard è un po' una roba privata forse non serve includerla, io includere solo polifemo e polifemobackend

**Comment by bob27aggiustatutto** [comment]
Come vuoi, tanto sono repo pubbliche quando viene rilasciata l'app

**Comment by bob27aggiustatutto** [comment]
https://app.clickup.com/t/8669fc92r

**Comment by bob27aggiustatutto** [comment]
https://github.com/PoliNetworkOrg/PoliFemo/pull/149
