### ISSUE TITLE
[Bug] Android: senza google play services, la sezione dettaglio aula presenta errori

### ISSUE THREAD

**Issue by bob27aggiustatutto** [PoliNetworkOrg/PoliFemo#132]
![immagine](https://user-images.githubusercontent.com/120955097/216837680-8e0e1939-b2ca-4317-8663-6021646170f4.png)

Risolvere o sostituire il componente con qualcos'altro per chi non ha android con google play services

Priorità: non prioritario

**Comment by toto04** [comment]
duplicato di #98

**Comment by bob27aggiustatutto** [comment]
se è lo stesso preciso componente sì, ma siccome l'avviso è diverso (uno ha la rotellina, l'altro ha il testo) ho immaginato fossero due componenti

**Comment by toto04** [comment]
mi sembra sia lo stesso messaggio di errore?
comunque la causa è la stessa, dovuta all'utilizzo della dependency nativa react-native-maps che a sua volta utilizza i google play services, utilizzata in entrambi i componenti

**Comment by bob27aggiustatutto** [comment]
no come ho scritto nell'altra issue non mi esce nessuna scritta, però sì, la causa è la stessa, vedi tu come le vuoi categorizzare le due cose

**Comment by toto04** [comment]
<img width="720" alt="image" src="https://user-images.githubusercontent.com/34661230/216839337-88aa096d-8010-434e-ae33-e851c2f7d2b4.png">
screenshot preso dall'immagine che hai allegato tu a #98, mi stai facendo sentire scemo 😅

**Comment by bob27aggiustatutto** [comment]
Sì ma non mi esce più, hai ragione dovevo dirlo

**Comment by toto04** [comment]
ah, estremamente interessante ahah, indagheremo meglio quando incominceremo a compilare app native dato che expo-go ha questa cosa dei google play services già dentro di se, comunque sì, è lo stesso problema

**Comment by bob27aggiustatutto** [comment]
![immagine](https://user-images.githubusercontent.com/120955097/216840118-db7d7dda-efb5-4e9f-b318-cd6cf67f6365.png)

questo vedo ora

**Comment by toto04** [comment]
bello ahah, puoi linkare la stessa immagine in #98? così abbiamo tutto nello stesso posto

**Comment by bob27aggiustatutto** [comment]
fatto
