### ISSUE TITLE
Unificare il sistema di icone in un unico hook

### ISSUE THREAD

**Issue by toto04** [PoliNetworkOrg/PoliFemo#139]
Adesso l'inserimento di icone SVG richiede un sacco di boilerplating, sia per skia che per le dimensioni
```ts
const svg = useSVG(icon.svg)

<Canvas
    style={{
        width: icon.width,
        height: icon.heigth,
    }}
>
    {svg && (
        <ImageSVG
            svg={svg}
            x={0}
            y={0}
            width={icon.width}
            height={icon.heigth}
        />
    )}
</Canvas>
```

dovrebbe diventare qualcosa tipo
```ts
const SVG = useSVGIcon(icon)

<SVG />
```

potenzialmente, si può rimuovere la necessità di utilizzare oggetti di configurazione della forma
```ts
    { svg: DataSourceParam; width: number; heigth: number }
```
con un transformer custom di metro (?)
magari questa cosa aiuterebbe anche con il preloading delle icone che ci mettono sempre un sacco a essere renderizzate la prima volta

**Comment by DiegoZaff** [comment]
Okay giusto, farebbe risparmiare molto tempo. Bisogna tenere conto che alcune icone necessitano di cambiare colore quando si passa da light a dark mode.
