### ISSUE TITLE
La status bar cambia colore dentro i modali

### ISSUE THREAD

**Issue by DiegoZaff** [PoliNetworkOrg/PoliFemo#140]
Penso succeda perché il modale viene renderizzato fuori dallo stack di navigazione.

Comunque è velocissimo da fixare.

**Comment by bob27aggiustatutto** [comment]
Probabilmente voi avete capito, io no, c'è qualche foto d'esempio per spiegare meglio?

**Comment by DiegoZaff** [comment]
![Screenshot_2023-02-15-13-31-02-523_host.exp.exponent.jpg](https://user-images.githubusercontent.com/43524162/219028128-800709f6-a2ab-4d10-8c84-89d5ad17c8fd.jpg)

Ad esempio qui, la status bar in alto dovrebbe essere bianca

**Comment by bob27aggiustatutto** [comment]
Io farei un mix fra il bianco e il colore del modale

**Comment by toto04** [comment]
huh potrebbe essere per via del fatto che è `<StatusBar>` è dentro a `<NavigationContainer>`, comunque dovremmo cambiare il modale anyway e usare qualcosa tipo https://www.npmjs.com/package/react-native-modal, il componente di default ha dei difetti, ad esempio l'animazione di fade è troppo lenta e non è customizzabile, magari vale la pena provare a vedere se usare questo componente risolve il problema

**Comment by DiegoZaff** [comment]
Si hai ragione, risolve il problema e ci sono anche le animazioni! 

Ho cambiato il modale del "aggiungi features" nel branch 8669hvbce come esempio.

**Comment by DiegoZaff** [comment]
Ho cambiato il modale del "aggiungi features" e le animazioni funzionano bene ma il problema del colore rimane (alla fine il modale di quella libreria è l'estensione di quello standard), anche aggiungendo un altra StatusBar dentro il modale non viene fixato, pensavo che fare cosi sarebbe bastato. Ci devo guardare meglio.

**Comment by DiegoZaff** [comment]
Ok, ho scoperto che con il nuovo modale la status bar cambiava colore a causa della prop coverScreen={true}. Probabilmente il modale coprendo tutto lo schermo sovrascriveva lo stile della status bar, la cosa strana è che non sembra sia modificabile da dentro o fuori il modale.

Il workaround che ho trovato sarebbe mettere coverScreen={false} e utilizzare la libreria react-native-portalize che permette di renderizzare il modale wrappato in un Portal sopra tutto il resto, in questo modo il modale continua a ricoprire tutto lo schermo anche se è innestato da qualche parte, e la status bar rimane come l'abbiamo impostata.

Se questo approccio va bene posso modificare anche gli altri modali.

#143

**Comment by toto04** [comment]
ma non è che è quel
```ts
            statusBarTranslucent={true}
```
che crea problemi?

**Comment by DiegoZaff** [comment]
Non penso, quella prop in teoria rende solo lo sfondo della status bar trasparente, come vogliamo che sia.
