### ISSUE TITLE
Login bug: se da backend mi cancellano, io dovrei riuscire a rimanere loggato

### ISSUE THREAD

**Issue by bob27aggiustatutto** [PoliNetworkOrg/PoliFemo#141]
Spiego cosa è successo

1. Ho fatto login con account polimi
2. tutto ok
3. dopo qualche giorno la tabella utenti viene spianata
4. La app crede che io sia loggato, ma non è vero.

Si dovrebbe fare un pezzo di codice che, all'apertura dell'app, fa una specie di auth-ping al backend, il quale se risponde che non sa chi sei (perché ti ha cancellato) all'utente rimangono 2 possibilità, lasciare che l'app (senza richiederti password) riprovi il login (attraverso una nuova API credo), oppure l'utente accetta che è disconnesso e si disconnette.

**Comment by toto04** [comment]
spostala nel backend se la vuoi
