### ISSUE TITLE
[FEATURE] Aggiungere un modo per copiare il proprio user id

### ISSUE THREAD

**Issue by francescolf** [PoliNetworkOrg/PoliFemo#151]
Per aiutare con il debug e con l'assegnazione dei permessi iniziale sarebbe comodo avere un'opzione che copia il proprio user id, magari dalle impostazioni in un modo simile alla dev mode di Android (premendo X volte una specifica opzione), o anche tramite una voce apposta.

**Comment by bob27aggiustatutto** [comment]
Giusto, la mettiamo nella sezione about https://github.com/PoliNetworkOrg/PoliFemo/pull/149
