### ISSUE TITLE
[BUG] Invisible news panel in dark mode

### ISSUE THREAD

**Issue by stignarnia** [PoliNetworkOrg/PoliFemo#160]
**Describe the bug**
Scrivo in italiano che fa già ridere il resto in inglese, il coso da tirare su per espandere il pannello delle notizie in modalità chiara si vede chiaramente che è una cosa diversa, in dark mode no.

Quello che succede è che non vedendolo uno tira su da centro schermo e verso l'alto e non si muove niente, finché non ti accorgi che devi strisciare dal basso dentro l'area delle notizie.

**Screenshots**
![Screenshot_20230219-222504_Expo Go.png](https://user-images.githubusercontent.com/80171209/219976239-ebd153d5-a6ba-441a-bd75-80224afaa8ec.png)

![Screenshot_20230219-222520_Expo Go.png](https://user-images.githubusercontent.com/80171209/219976238-c7d76cc9-10b2-4ea1-afbe-7fc25fa06c3b.png)

**Describe your environment:**
Versione 1.0.0
Build 181
OS: Android 12 - MI9
env: expo - storeClient

**Comment by toto04** [comment]
Anche se questa è stata aperta prima la chiudo in favore di #164 che è la stessa ma più completa
