### ISSUE TITLE
[BUG] Links in news articles are not followable

### ISSUE THREAD

**Issue by EndBug** [PoliNetworkOrg/PoliFemo#162]
**Describe the bug**
When you click a link in a news article, the article content goes blank

**Steps to reproduce**

1. Go to "News"
2. Open a category
3. Open an article
4. Click on the usual "more info"

**Expected behavior**
Either open an in-app browser that is detachable or directly open the OS browser.

**Screenshots**
![image](https://user-images.githubusercontent.com/26386270/220061296-46150262-964c-4910-8b7d-bcb4d39a6985.png)
![image](https://user-images.githubusercontent.com/26386270/220061323-f60c62b1-f21e-4710-aac9-1d49e2139f68.png)

**Describe your environment:**
(You can find this information in Settings > About this app)
 - Device: Pixel 3a
 - OS: Android 12
 - Client: Expo Go
 - Version: stable

**Comment by toto04** [comment]
fixed in #210
