### ISSUE TITLE
[BUG] Some news categories fade to background

### ISSUE THREAD

**Issue by EndBug** [PoliNetworkOrg/PoliFemo#163]
**Describe the bug**
Some news categories don't have a background, or at least it can't be accessed by the client.

**Screenshots**
![image](https://user-images.githubusercontent.com/26386270/220063884-e5c8668a-62e0-4560-8894-09c1fe25c3d4.png)

**Describe your environment:**
(You can find this information in Settings > About this app)
 - Device: Pixel 3a
 - OS: Android 12
 - Client: Expo Go
 - Version: stable

**Comment by bob27aggiustatutto** [comment]
Workaround: ricarica tutta l'app, non ti ha caricato l'immagine

**Comment by toto04** [comment]
riapro questa issue perché abbiamo deciso di usare [blurhash](https://blurha.sh/) per mostrare qualcosa di decente mentre le immagini vengono scaricate da remoto / se c'è un errore di caricamento, dato che questa cosa può decisamente succedere in prod

**Comment by toto04** [comment]
fixed in #198
