### ISSUE TITLE
[BUG] News modal behavior is not clear

### ISSUE THREAD

**Issue by EndBug** [PoliNetworkOrg/PoliFemo#164]
**Describe the bug**
As of now, the modal icon in dark theme kind of looks like a separator when the modal is closed. In light mode you can only see a light shadow.

**Expected behavior**
I think that the modal should also open if the user scrolls down in the main content. A thicker shadow would also help.

**Screenshots**
![image](https://user-images.githubusercontent.com/26386270/220065448-78baf21f-3d29-4eed-b20c-64d0870c617a.png)
![image](https://user-images.githubusercontent.com/26386270/220065477-3cc98024-711c-4f09-8041-d3395168f988.png)

**Describe your environment:**
 - Device: Pixel 3a
 - OS: Android 12
 - Client: Expo Go
 - Version: stable

**Comment by bob27aggiustatutto** [comment]
Centra https://github.com/PoliNetworkOrg/PoliFemo/pull/143?

**Comment by EndBug** [comment]
No

**Comment by toto04** [comment]
per quanto riguarda il behavior dello scroll credo sia previsto così da design, questo è legato all'overarching problem che le API per le ombre native di android sono schifosamente inutili, quello sicuramente bisogna trovare un modo per sistemarlo, qui e in tutti gli altri punti dell'app in cui ci sono ombre

**Comment by toto04** [comment]
Confermo che il behavior dello scroll è così da design, consultando in generale l'idea di scrollare verso in alto in qualsiasi punto della home non sembra essere troppo favorita, anche perché sarebbe un po' in conflitto con l'handling delle gestures del menu e della sezione highlights.
Il sistema di rendering delle ombre è stato rifatto da zero che aumenta vertiginosamente la visibilità della sezione, ed è già stata messa in main, dunque considero questa cosa fixata
