### ISSUE TITLE
[FEATURE] Add All Contributors to the repo

### ISSUE THREAD

**Issue by EndBug** [PoliNetworkOrg/PoliFemo#165]
**Is your feature request related to a problem? Please describe.**
The only contributors listed are the ones that have pushed to the repo in the [Contributors](https://github.com/PoliNetworkOrg/PoliFemo/graphs/contributors) tab.

**Describe the solution you'd like**
Adding [All Contributors](https://allcontributors.org/) would allow crediting every contributor and list their contribution type.

**Comment by bob27aggiustatutto** [comment]
Solo quelli che vogliono essere menzionati

**Comment by EndBug** [comment]
Closed by #193
