### ISSUE TITLE
[FEATURE] Webview app polimi

### ISSUE THREAD

**Issue by bob27aggiustatutto** [PoliNetworkOrg/PoliFemo#166]
Aggiungere da qualche parte l'app del polimi, se sei loggato

**Comment by toto04** [comment]
perché dovremmo fare una cosa del genere?

**Comment by stignarnia** [comment]
in realtà se è facile sarebbe carino, invoglia la gente a scaricarla prima che ci sia feature parity tra le due, mica hanno voglia di tenerne due se c'è una funzione di quella ufficiale che gli serve non scaricano la nostra

**Comment by stignarnia** [comment]
come se fossi il poli avrei mantenuto la vecchia app nella nuova per le funzioni che non hanno...

**Comment by toto04** [comment]
dobbiamo tenere a mente due cose: 
1. non possiamo pubblicare questa webview sugli store, non ce l'approverebbero mai
2. non pubblichiamo l'app ufficialmente al pubblico intero finché non c'è feature parity, la gente deve scaricare quest'app e immediatamente dire che l'app del poli non serve più

**Comment by bob27aggiustatutto** [comment]
Giusto,  infatti si vede solo tramite expo go

**Comment by stignarnia** [comment]
> dobbiamo tenere a mente due cose:
> 
> 1. non possiamo pubblicare questa webview sugli store, non ce l'approverebbero mai
> 2. non pubblichiamo l'app ufficialmente al pubblico intero finché non c'è feature parity, la gente deve scaricare quest'app e immediatamente dire che l'app del poli non serve più

Ah se la logica è questa ha senso non farlo

**Comment by toto04** [comment]
stale? ma si dai chiamiamola stale, ottima scusa
