### ISSUE TITLE
[BUG] I think Expo Go doesn't show all branches

### ISSUE THREAD

**Issue by stignarnia** [PoliNetworkOrg/PoliFemo#172]
**Describe the bug**
Non si vedono tutti i branch nella lista di Expo Go, tipo quello dove sono già disponibili le aule

**Steps to reproduce**
Expo Go -> Polifemo -> See all branches

**Expected behavior**
Vedere gli stessi branch di questa repo

**Screenshots**
![Screenshot_20230224-101915_Expo Go.png](https://user-images.githubusercontent.com/80171209/221151968-02a6b919-b8c7-42cf-aa46-6e3adafa0015.png)

**Describe your environment:**
Versione 1.0.0
Build 185
OS: Android 12 - MI9
env: expo - storeClient

**Comment by toto04** [comment]
ma wut, questo era un problema già successo in precedenza, ma credevo di averlo fixato mettendo `fetch-depth: 0` al checkout step del workflow, sinceramente non riesco a immaginarmi perché dovrebbe scomparire un singolo branch dai remote nell'action quando chiaramente esiste ancora lmao, vedrò di indagare

**Comment by bob27aggiustatutto** [comment]
Perché il branch dettaglio aule è stato mergiato nel branch delle aule, credo

**Comment by stignarnia** [comment]
ma tanto non c'è nessuno dei due

**Comment by bob27aggiustatutto** [comment]
Quel del dettaglio aule è giusto non ci sia perché è stato eliminato con il merge dentro il branch ffu delle aule

**Comment by stignarnia** [comment]
si va bene ho capito ma non c'è nè quella né ffu

**Comment by toto04** [comment]
vabbè a parte che non ho mai capito perché non ci fosse il branch ffu ogni tanto (era a caso boh idk) questo non è tanto importante tanto il push su EAS è solo per comodità e si può sempre far partire il branch in locale, tanto adesso ci sposteremo sempre di più verso i canali di beta testing ufficiali.

quindi boh sti cazzi la considero won't fix
