### ISSUE TITLE
[FEATURE] Issue template anche sul backend + interazione clickup delle issue

### ISSUE THREAD

**Issue by bob27aggiustatutto** [PoliNetworkOrg/PoliFemo#174]
Aggiungere issue template anche sul backend https://github.com/PoliNetworkOrg/PoliFemoBackend

**Comment by bob27aggiustatutto** [comment]
Si intende ovviamente anche l'integrazione clickup delle issue

**Comment by toto04** [comment]
l'integrazione c'è già, per le template mettile e basta direttamente no? se vuoi copiarle fai pure, ma tanto sono un edit di 30 secondi rispetto a quelle di default, se vuoi qualcosa di pensato meglio apri direttamente una issue nel backend

**Comment by bob27aggiustatutto** [comment]
fai pure tu tutto e chiudi questa issue quando fatto

**Comment by bob27aggiustatutto** [comment]
1. https://github.com/PoliNetworkOrg/PoliFemoBackend/commit/64272b22e9b24ff7f3c61c121b6e46817409f8f0
2. https://github.com/PoliNetworkOrg/PoliFemoBackend/commit/bc01f9c7b04360c1611ec13c2561d5cbf0ac64fb

**Comment by bob27aggiustatutto** [comment]
pensavo di aver fatto ma non va, chiedo aiuto

**Comment by francescolf** [comment]
Risolto. La cartella `ISSUE_TEMPLATE` andava messa dentro `.github`
