### ISSUE TITLE
[BUG] Il dettaglio aula si deve aprire anche se non siamo pronti

### ISSUE THREAD

**Issue by bob27aggiustatutto** [PoliNetworkOrg/PoliFemo#179]
Attualmente se apri un dettaglio di un'aula passa qualche secondo e poi si apre

Dovrebbe accedere il contrario, schiaccio e si apre subito la pagina, anche vuota, si riempirà da sola appena può

Altrimenti la percezione è non aver cliccato

L'alternativa è dirottare subito su una pagina intermedia di attesa, di modo che l'utente sa che il suo click è stato registrato

**Comment by toto04** [comment]
si non credo che serva aprire una issue e quindi una task apposta per questa cosa dai, commenta direttamente sulla pr delle aule libere così anche Matteo lo vede più velocemente

**Comment by bob27aggiustatutto** [comment]
fixato, credo in questo commit https://github.com/PoliNetworkOrg/PoliFemo/commit/749ae7bcfcf0624c3b71aeda10c76ac9790b7aaa ma è fixato
