### ISSUE TITLE
[FEATURE] Aggiungere titolo della notizia in evidenza

### ISSUE THREAD

**Issue by bob27aggiustatutto** [PoliNetworkOrg/PoliFemo#182]
**Is your feature request related to a problem? Please describe.**
"In evidenza" non ti dice ad occhio di che cosa si parla
![immagine](https://user-images.githubusercontent.com/120955097/222956688-f00e9d5e-241a-4532-9799-8d42a57e6ab0.png)

**Describe the solution you'd like**
Vorrei che lì nel cerchio rosso, dentro al rettangolo della notizia d'evidenza, sul basso, ci sia il titolo della notizia in evidenza

**Comment by toto04** [comment]
si effettivamente così com'è adesso nemmeno si capisce che quello è un articolo vero e proprio e non una sezione come le altre

**Comment by DiegoZaff** [comment]
Andrebbe chiesto al design come deve essere fatto questo titolo

**Comment by bob27aggiustatutto** [comment]
pr in #185
