### ISSUE TITLE
[BUG] mappa delle aule inizia alle coordinate null, null su android

### ISSUE THREAD

**Issue by stignarnia** [PoliNetworkOrg/PoliFemo#201]
**Describe the bug**
Il titolo

**Steps to reproduce**
Apri la funzione aule, clicca su mappa, vedi tutto blu. Poi zoomando indietro e spostandoti dal corno d'Africa a milano funziona.

**Expected behavior**
centrarsi sulla posizione dell'utente

**Comment by stignarnia** [comment]
A me sembra che, quando non crasha, non lo faccia più, sarebbe il caso di chiuderlo e sostituirlo con https://github.com/PoliNetworkOrg/PoliFemo/issues/242 ?

**Comment by lups2000** [comment]
@stignarnia in realtà l'avevo testato ormai 3 settimane fa e lo faceva, ora dovrebbe essere fixato(pr ancora aperta)

**Comment by toto04** [comment]
risolta con #236
