### ISSUE TITLE
[BUG] Articoli non visibili in main

### ISSUE THREAD

**Issue by angeousta** [PoliNetworkOrg/PoliFemo#208]
**Describe the bug**
Non si vedono più gli articoli

**Steps to reproduce**

1. Aprire l'app
2. Branch main
3. Aprire una categoria
4. Non ci sono gli articoli

**Expected behavior**
Ci sono degli articoli

**Screenshots**
![immagine](https://user-images.githubusercontent.com/132761637/236628281-9723ebd0-66da-4107-9be7-e9ecb3349adb.png)

**Comment by toto04** [comment]
fixed as of #210
