### ISSUE TITLE
[BUG] articoli simili?

### ISSUE THREAD

**Issue by bob27aggiustatutto** [PoliNetworkOrg/PoliFemo#223]
![IMG_20230701_102238_651](https://github.com/PoliNetworkOrg/PoliFemo/assets/120955097/df7654e3-9e8e-4ffc-905b-144c2e2d17a7)

I primi due articoli sembrano "doppi"

**Comment by bob27aggiustatutto** [comment]
![IMG_20230701_102607_889](https://github.com/PoliNetworkOrg/PoliFemo/assets/120955097/26ecbf53-e724-458e-9f5b-dec72ed966c6)

**Comment by DiegoZaff** [comment]
Penso ci siano duplicati in database, ad esempio l'articolo 27 e 28.

**Comment by bob27aggiustatutto** [comment]
Non sono duplicati, il titolo è simile ma non uguale nella prima foto

**Comment by DiegoZaff** [comment]
Ah giusto, my bad. Può essere che il poli abbia cambiato url e titolo dell'articolo e il nostro database si sia aggiornato con quello modificato senza cancellare quello precedente? Ad ogni modo mi sembra qualcosa che riguardi il backend.

**Comment by francescolf** [comment]
> Ah giusto, my bad. Può essere che il poli abbia cambiato url e titolo dell'articolo e il nostro database si sia aggiornato con quello modificato senza cancellare quello precedente? Ad ogni modo mi sembra qualcosa che riguardi il backend.

Questo. Cambiando il titolo è cambiato anche l'url, quindi è stato inserito due volte. Ho cancellato le versioni vecchie.

**Comment by bob27aggiustatutto** [comment]
OK cancellare ma allora dobbiamo aprire un bug sulla repo backend per evitare o almeno provare ad evitare che si ripeta
