### ISSUE TITLE
[BUG] Accesso con CIE livello 2 semi rotto

### ISSUE THREAD

**Issue by stignarnia** [PoliNetworkOrg/PoliFemo#238]
**Describe the bug**
Se provi ad accedere con CIE senza usare né la scansione della carta (livello 3) né inserendo username e password e poi confermando la notifica, ma cliccando direttamente il tasto per aprire l'app CIE, essa non si apre. Pensavo fosse impossibile farlo andare in una WebView così però poi schiacciando il badge di Google play che ti propone non riuscendo ad aprire l'app si apre Google Play, quindi penso che siano fattibili questo tipo di collegamenti.

**Steps to reproduce**
https://github.com/PoliNetworkOrg/PoliFemo/assets/80171209/90d18a37-e191-4c44-aa7d-17f1b172b7d3

**Describe your environment:**
Versione 1.0.0
Build 215
OS: Android 12 - MI 9
env: expo - storeClient
GMS: unknown

**Comment by toto04** [comment]
Questo purtroppo è colpa degli sviluppatori dell'app CIE, essendo che la pagina non ricontrolla l'avvenuto login e aspetta un redirect esterno (a differenza di tipo PosteID), funzionerebbe se potessimo usare un flow OAuth normale ma non è così essendo che dobbiamo fare tutto il passaggio strano nella webview per ottenere il token del politecnico. Per adesso lascio aperta nell'evenienza che qualcuno trovi un workaround furbo ma non credo sia possibile

**Comment by toto04** [comment]
ok update, io e @angeousta abbiamo valutato l'opzione di deep linking per continuare il flusso oauth in app, ma questa cosa avrebbe impressionanti drawback a livello di esperienza utente (ovvero ogni volta che si fa un qualsiasi login con CIE si verrebbe promptati di aprire polifemo)

questo problema è aggirabile usando altri sistemi di login (disattivando 2fa e poi tramite credenziali) e la sessione dovrebbe durare per tempo indeterminato anyway. se i developer del sistema CIE un giorno aggiornano la pagina per fare check automatici come quella di PosteID la cosa viene fixata in automatico, quindi sta issue può essere chiusa
