### ISSUE TITLE
Bug: la barra di ricerca scompare quando la clicco, e posso scriverci ancora anche se non si vede

### ISSUE THREAD

**Issue by steven9463912** [PoliNetworkOrg/PoliFemo#37]
https://user-images.githubusercontent.com/96684523/198143411-37ad0222-fb2c-47ea-af07-9806949f500b.mp4

**Comment by toto04** [comment]
For the Record: a quanto pare questo era dovuto a come Android gestisce la dimensione delle finestre in relazione all'apertura della tastiera in generale: https://developer.android.com/guide/topics/manifest/activity-element#wsoft
di default veniva ridimensionata causando lo spostamento del BottomSheet, ora come su iOS il contenuto viene semplicemente spostato quando necessario, lasciano le dimensioni della finestra invariate.
L'impostazione relativa in app.json per Expo è https://docs.expo.dev/versions/v46.0.0/config/app/#softwarekeyboardlayoutmode

Fixato nel branch [feature/CU-31f1dpb](https://github.com/PoliNetworkOrg/PoliFemo/tree/feature/CU-31f1dpb) per facilitare il testing della barra di ricerca.
