### ISSUE TITLE
[Bug] Visualizzazione filtro non si riposiziona

### ISSUE THREAD

**Issue by steven9463912** [PoliNetworkOrg/PoliFemo#42]
https://user-images.githubusercontent.com/96684523/200164342-ac8faf79-9e4a-4b17-aa2b-28fad9060158.mp4

Come si vede in video, filtrando con la ricerca un qualcosa che è in fondo (come `Valutazioni`), si nota che la ricerca non riporta la visualizzazione ai primi elementi, così facendo rimaniamo "a destra" dove c'è vuoto causa il filtro applicato.

Spero sia chiaro

**Comment by toto04** [comment]
il bug dovrebbe essere stato risolto aggiungendo uno scrollTo come side-effect al cambiamento del filtro di ricerca.
su iOS il bug non era presente poiché il ridimensionamento del contenuto della scrollview modificava già la posizione, ho testato su emulatore Android e sembra funzionare.
adesso il menu si riposiziona fluidamente nella posizione iniziale qualsiasi ricerca si effettua, anche su iOS ora la posizione si aggiorna anche se il contenuto non diventa più stretto dell'intera finestra, a differenza di prima
