### ISSUE TITLE
[Bug] Inserimento nuova features nel momento in cui è già in corso una ricerca

### ISSUE THREAD

**Issue by Tammura** [PoliNetworkOrg/PoliFemo#43]
Quando inserisco una nuova feature che sto cercando, la feature si agginuge correttamente ma poi rimane disponibile per l'aggiunta nuova features e quindi poi la features rimane disponibile due volte:

https://user-images.githubusercontent.com/72708024/200177871-e8588ff9-e79b-4b5c-aea8-123dd8be8059.MP4

**Comment by toto04** [comment]
dovrebbe essere fixato nel branch [feature/CU-35303pf](https://github.com/PoliNetworkOrg/PoliFemo/tree/feature/CU-35303pf), riesci a controllare in Expo Go se funziona tutto as expected?
