### ISSUE TITLE
[Bug] colori sbagliati in dark mode (android)

### ISSUE THREAD

**Issue by cosimonegri** [PoliNetworkOrg/PoliFemo#54]
![Screenshot_2022-11-11-13-17-13-914_host exp exponent](https://user-images.githubusercontent.com/93294521/201340676-b1dfc95c-a2c3-4fbd-9fbe-8d787a8ccd44.jpg)

Device: Xiaomi Mi 10 Lite

Si vede bene che il titolo "PoliFemo" è diverso da quello su Figma e la scritta "In Evidenza" dovrebbe essere un po' più scura del titolo "News". Anche altri colori ci sta che siano un leggermente diversi.

Cercando un po' su internet, mi pare di aver capito che talvolta i dispositivi android (o perlomeno Xiaomi) applicano in dark mode delle specie di filtri che modificano i colori del codice.

L'unica soluzione che ho trovato sarebbe quella di aggiungere una riga che blocca questo comportamento in un file nella cartella "Android", ma usando Expo non so se si possa fare.

**Comment by toto04** [comment]
oof questo sì che è strano, puoi linkare qui quello che hai trovato a riguardo? magari expo da accesso alla riga di cui parli nel file `app.json`

**Comment by cosimonegri** [comment]
1) https://stackoverflow.com/questions/63762675/react-native-android-dark-mode-issue

2) https://stackoverflow.com/questions/70258607/react-native-expo-android-dark-mode-issue

3) https://stackoverflow.com/questions/66368126/text-color-is-overridden-to-white-when-tested-on-a-device-with-android-10-in-dar

Il primo riguarda react native.

Il secondo riguarda react native expo. Magari funziona, però c'erano un po' di robe da fare, e non essendo molto pratico volevo evitare di sminchiare qualcosa.

Il terzo non mi convince molto, ma te lo linko comunque.

**Comment by toto04** [comment]
Oh Gesù cristo.
quindi niente la "soluzione" che a quanto pare tutti sono costretti a implementare è togliere la dark mode da android automatica e farla a mano. 😀👍

**Comment by toto04** [comment]
chiudo questa issue dato che non sono stati fatti progressi da innumerevoli mesi e non riusciamo nemmeno più a riprodurre la cosa per carenza di dispositivi con questo problema, in caso sia ancora presente si può riaprire
