### ISSUE TITLE
[Bug] Le X sono tagliate nella homepage

### ISSUE THREAD

**Issue by steven9463912** [PoliNetworkOrg/PoliFemo#61]
![immagine](https://user-images.githubusercontent.com/96684523/205274223-31fa7c93-674b-4a4b-a987-3d0bb300aca3.png)

**Comment by lups2000** [comment]
Aggiungo per quelli che magari non avevano letto la chat su Discord che il problema c’è solo per Android!I margini che sono impostati ora sono già corretti per IOS, quindi eventualmente c’è da porre una condizione nel caso di Android in cui si va ad aumentare un pelo il margine superiore.

**Comment by toto04** [comment]
linked alla task [CU-34g7wcz](https://app.clickup.com/t/34g7wcz) già assegnata ad @AndreaTorti-01
