### ISSUE TITLE
Che fare della branch feature/CU-37hf2du?

### ISSUE THREAD

**Issue by steven9463912** [PoliNetworkOrg/PoliFemo#69]
Che fare della branch feature/CU-37hf2du?

https://github.com/PoliNetworkOrg/PoliFemo/tree/feature/CU-37hf2du

**Comment by toto04** [comment]
boh, il workflow in teoria dovrebbe creare una task nei problems di clickup per ogni issue aperta, non so se vogliamo aggiungerci qualche altra cosina decorativa, tipo aggiungere la task nell'ultimo sprint o commentare su GitHub che la task è stata creata
