### ISSUE TITLE
[Bug] linea che divide la sezione va oltre la sezione genitore

### ISSUE THREAD

**Issue by Tammura** [PoliNetworkOrg/PoliFemo#73]
Su IOS la linea che divide le sezioni va oltre la sezione genitore come mostrato nel video.

https://user-images.githubusercontent.com/72708024/208305843-0b3312ec-1cc4-4c38-bd37-354bcfb30c0b.MP4

**Comment by toto04** [comment]
risolto nell'[ultimo commit](https://github.com/PoliNetworkOrg/PoliFemo/pull/71/commits/ba4ce56fc2666432f159f34a77b53d5a40917ba1)

**Comment by bob27aggiustatutto** [comment]
si attende il merge di #71 per chiudere questa issue

**Comment by toto04** [comment]
si il mio ragionamento per chiuderla era che il bug non è presente in main, era solo nel branch stesso, e ora è fixato
link la pr

**Comment by bob27aggiustatutto** [comment]
ah, ti chiedo scusa, non avevo letto da nessuna parte che il bug riguardava una branch in particolare.

per ora va così, attendiamo il merge per chiudere 👍
