### ISSUE TITLE
[Bug] Le X sono tagliate nella homepage - E non sono cliccabili

### ISSUE THREAD

**Issue by bob27aggiustatutto** [PoliNetworkOrg/PoliFemo#74]

**Comment by bob27aggiustatutto** [comment]
![immagine](https://user-images.githubusercontent.com/120955097/208326099-f2ba0620-a2d9-435f-b578-af072c5e3f98.png)

**Comment by bob27aggiustatutto** [comment]
Aggiungo per quelli che magari non avevano letto la chat su Discord che il problema c’è solo per Android!I margini che sono impostati ora sono già corretti per IOS, quindi eventualmente c’è da porre una condizione nel caso di Android in cui si va ad aumentare un pelo il margine superiore.

**Comment by bob27aggiustatutto** [comment]
linked alla task [CU-34g7wcz](https://app.clickup.com/t/34g7wcz) già assegnata ad @AndreaTorti-01

**Comment by bob27aggiustatutto** [comment]
old issue #61

**Comment by bob27aggiustatutto** [comment]
in questa branch ora si vedono bene
https://github.com/PoliNetworkOrg/PoliFemo/tree/feature/CU-34g7wcz

tuttavia non succede nulla se premo la X

**Comment by bob27aggiustatutto** [comment]
cc @pontig

**Comment by bob27aggiustatutto** [comment]
@pontig guarda qui

1. https://github.com/PoliNetworkOrg/PoliFemo/tree/test-fix-74 
2. https://github.com/PoliNetworkOrg/PoliFemo/commit/2a472dd145022f53edd3ab0cf7af17a0a1d52f45

Così funziona. Le X sono cliccabili. Certo, è tutta sbagliata la grafica, ma era solo per darti un feedback

**Comment by toto04** [comment]
magari questo può essere utile https://reactnative.dev/docs/pressable#hitslop

**Comment by bob27aggiustatutto** [comment]
Titolo cambiato in "[Bug] Le X sono tagliate nella homepage - E non sono cliccabili"
