### ISSUE TITLE
Che fare della branch feature/CU-37hf2du?

### ISSUE THREAD

**Issue by bob27aggiustatutto** [PoliNetworkOrg/PoliFemo#75]

**Comment by bob27aggiustatutto** [comment]
Che fare della branch feature/CU-37hf2du?

https://github.com/PoliNetworkOrg/PoliFemo/tree/feature/CU-37hf2du

**Comment by bob27aggiustatutto** [comment]
boh, il workflow in teoria dovrebbe creare una task nei problems di clickup per ogni issue aperta, non so se vogliamo aggiungerci qualche altra cosina decorativa, tipo aggiungere la task nell'ultimo sprint o commentare su GitHub che la task è stata creata

ho messo nel workflow una singola chiamata cURL per creare la task e non ci ho più lavorato, se qualcun altro ha qualche cosa da aggiungerci / feedback sentitevi liberi di metterci mano

**Comment by bob27aggiustatutto** [comment]
old issue #69

**Comment by toto04** [comment]
la cosa del workflow è stata ultimata e il branch è merged
