### ISSUE TITLE
[Bug?] Due tasti "indietro" nella home

### ISSUE THREAD

**Issue by bob27aggiustatutto** [PoliNetworkOrg/PoliFemo#76]

**Comment by bob27aggiustatutto** [comment]
![immagine](https://user-images.githubusercontent.com/120955097/208326151-483bcac8-4887-4aac-8ba8-b0e7fea7f224.png)

**Comment by bob27aggiustatutto** [comment]
Qui si vede sia "back" che il tasto "home" ma entrambi fanno la stessa cosa

**Comment by bob27aggiustatutto** [comment]
old issue #70

**Comment by toto04** [comment]
se ci pensi qualsiasi cosa fai dalla home ha come conseguenza il fatto che questi due tasti facciano la stessa cosa (e.g, se entri nella sezione aule libere, nella prima pagina entrambi i tasti riportano alla home, solo una volta che si incomincia a navigare nei sotto menu il tasto indietro incomincia a comportarsi diversamente dal tasto home)

a livello di UX ha senso NON modificare la navbar in base allo stato di navigazione per non aumentare la confusione, l'opinione generale è che non diano troppo fastidio
