### ISSUE TITLE
[Bug] prune-branches workflow non funziona se sono aperti troppi branch su EAS

### ISSUE THREAD

**Issue by toto04** [PoliNetworkOrg/PoliFemo#85]
lo script [prune-branches.js](../blob/master/scripts/prune-branches.js) crasha con errore:
```
RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded
```

va aumentato lo stdio buffer per il child process
```sh
eas branch:list --json --non-interactive
```
(default è 200KB, può essere tranquillamente aumentato a qualcosa nell'ordine dei MB)

**Comment by bob27aggiustatutto** [comment]
chiuso in #92
