### ISSUE TITLE
[Design] Tasti "conferma", "ok", "annulla", sono molto "old-style"

### ISSUE THREAD

**Issue by bob27aggiustatutto** [PoliNetworkOrg/PoliFemo#86]
Tasti "conferma", "ok", "annulla", sono molto "old-style"

Mi aspetterei delle icone/emoji carine al loro posto 

![immagine](https://user-images.githubusercontent.com/120955097/209958450-42fae60a-0190-49f0-9a51-acd5cc8a7e7f.png)

![immagine](https://user-images.githubusercontent.com/120955097/209958493-aa2f59a8-3260-4828-9430-90dfc998da73.png)

**Comment by bob27aggiustatutto** [comment]
assegno a @toto04  e @Tammura  per discuterne coi designers

**Comment by Tammura** [comment]
Va bene, iniziò a parlarne con le designers e poi vi aggiorno!

**Comment by toto04** [comment]
le designer hanno segnato questa issue come no-fix
le scritte sono più coerenti di icone, l'opinione generale è che sia meglio così
