### ISSUE TITLE
[Design] Scritta in alto a SX al posto del vuoto

### ISSUE THREAD

**Issue by bob27aggiustatutto** [PoliNetworkOrg/PoliFemo#89]
![immagine](https://user-images.githubusercontent.com/120955097/209995475-c131049d-caa4-4e86-8864-734d000a49e9.png)

Io qui scriverei "aule libere"
O comunque il titolo in cui siamo
Però questa mi sa che è una cosa generica, non riguarda solo questa pagina

**Comment by lups2000** [comment]
Bisognerebbe sentire le designers, mi sto attendendo alla versione di frigna più recente

**Comment by bob27aggiustatutto** [comment]
https://app.clickup.com/t/863ft4x9k
