### ISSUE TITLE
[Design] Login in dark mode attualmente fa schifo

### ISSUE THREAD

**Issue by bob27aggiustatutto** [PoliNetworkOrg/PoliFemo#90]
![immagine](https://user-images.githubusercontent.com/120955097/209995554-7aca83e5-9b2f-4491-b173-24bfed506f78.png)

Fa veramente schifo in dark mode

**Comment by toto04** [comment]
devo precisare: l'intera pagina di login è un grosso placeholder, devo spiegare ai designer quali sono i requirements per questa pagina e avere il design fatto ad-hoc

argomentabilmente il tema chiaro fa schifo uguale lmao

**Comment by bob27aggiustatutto** [comment]
https://app.clickup.com/t/862hz4rg9
