### ISSUE TITLE
App android crasha dopo il login con navigation.GoBack()

### ISSUE THREAD

**Issue by DiegoZaff** [PoliNetworkOrg/PoliFemo#93]
L'app crasha su Android dopo aver effettuato il login quando viene invocata navigation.goBack().

`void api.setTokens({ poliNetworkToken, polimiToken }).then(() => {
                setTimeout(() => {
                    navigation.goBack()
                }, 1000)
            })
`

Il problema sembra legato a questa [issue](https://github.com/react-native-webview/react-native-webview/issues/1915)

Ho testato che aggiungere `androidLayerType="software"` alle prop della WebView sembra risolvere il problema.

**Comment by toto04** [comment]
questo dovrebbe essere stato fixato in main con il merge di #94, qualcun altro con android può confermare?
@bob27aggiustatutto @cosimonegri

**Comment by francescolf** [comment]
Posso confermare 👍

**Comment by cosimonegri** [comment]
Confermo anche io

**Comment by bob27aggiustatutto** [comment]
Non posso confermare poiché per ora c'è solo il login con polimi e non voglio farlo per ora

**Comment by toto04** [comment]
era un problema con la webview, non con il login di per se, funziona qua funziona ovunque 👌
