### ISSUE TITLE
[Bug] La lista dei campus usa troppo spazio vuoto sotto

### ISSUE THREAD

**Issue by bob27aggiustatutto** [PoliNetworkOrg/PoliFemo#99]
![immagine](https://user-images.githubusercontent.com/120955097/212557283-6463a323-5dcd-4b06-bfd2-b4d28deda3a9.png)

Come si vede dalla foto, c'è troppo spazio vuoto tra i due tasti (back e home) e la fine dei tasti campus

![immagine](https://user-images.githubusercontent.com/120955097/212557321-fe8c451b-8797-4f58-9d7f-bdbd4f9f1197.png)

**Comment by lups2000** [comment]
Ok grazie,la lista degli edifici e delle aule invece come è?

**Comment by bob27aggiustatutto** [comment]
![immagine](https://user-images.githubusercontent.com/120955097/212557884-fcbb73eb-7645-40e2-bf20-2cb6b66665c1.png)

**Comment by lups2000** [comment]
Ma scorre?inoltre la posizione non l’hai abilitata tu oppure non funziona?Dovrebbe comparire la via sopra

**Comment by bob27aggiustatutto** [comment]
1) Scorre
2) Nello screen avevo il GPS spento, l'ho acceso ma non cambia, probabilmente non prende dove mi trovo ora

**Comment by bob27aggiustatutto** [comment]
Se hai il GPS spento la rotellina 
![immagine](https://user-images.githubusercontent.com/120955097/212561079-544efb0e-177f-4f31-a7f7-cf9929af3c30.png)
 non dovrebbe neanche mostrarsi, non credi?

**Comment by lups2000** [comment]
In realtà avevo messo una rotellina che continuava a girare finché non trovava il segnale di gps,mi sembrava carino

**Comment by lups2000** [comment]
https://user-images.githubusercontent.com/100372313/212561308-5105fb15-508b-451f-96bf-23a43bde4e9e.MOV

**Comment by bob27aggiustatutto** [comment]
Da me non gira, e se il gps è spento non deve esistere, se no gira a vuoto

**Comment by lups2000** [comment]
C’è da sentire i designer ma a mio parere ci sta che giri a vuoto finché non becchi il gps,se è spento amen,avere una freccetta così fluttuante se non c’è segnale lo trovo proprio brutto!

**Comment by bob27aggiustatutto** [comment]
Spostiamo la discussione del GPS su #101 e lasciamo questa issue per parlare dello spazio in eccesso

**Comment by lups2000** [comment]
Mi controlleresti ora come è? Non avendo android sto facendo un pò di fatica! grazie

**Comment by toto04** [comment]
btw to chime in, per questo tipo di issue ti consiglio di scaricare android studio e testare su un emulatore di android, è estremamente rapido e facile

**Comment by lups2000** [comment]
> btw to chime in, per questo tipo di issue ti consiglio di scaricare android studio e testare su un emulatore di android, è estremamente rapido e facile

Si ce l’ho però ho selezionato solo un dispositivo che ha lo schermo con le stesse dimensioni del mio iPhone,andava tutto bene quando lo avevo testato!Si vede che lui ha uno schermo più grande e vedeva il taglio

**Comment by bob27aggiustatutto** [comment]
![immagine](https://user-images.githubusercontent.com/120955097/212766172-743a0338-a25e-459b-aa4d-16c764aa0e25.png)

**Comment by bob27aggiustatutto** [comment]
per la branch https://github.com/PoliNetworkOrg/PoliFemo/tree/feature/CU-861m3wffu

questo è quello che vedo ora 

![immagine](https://user-images.githubusercontent.com/120955097/213699523-a7ef59d8-8edb-43b0-8aa4-c3c62f74b267.png)


![immagine](https://user-images.githubusercontent.com/120955097/213699538-4587e677-3574-4f8b-aba3-9bc69398dd22.png)


direi tutto sommato meglio di prima, quindi direi che questa issue si può chiudere

**Comment by lups2000** [comment]
bene, ma la lista degli edifici scorre ?

**Comment by bob27aggiustatutto** [comment]
Sì, sembra tutto giusto

**Comment by toto04** [comment]
fixed nell'unico branch affected, chiudo
